apiVersion: 1

datasources:
  - name: Trino
    type: trino-datasource
    access: proxy
    url: http://trino:8080
    jsonData:
      catalog: iceberg
      schema: gold
      user: grafana
    isDefault: true
    editable: true
